### ISSUE TITLE
active day

### ISSUE THREAD

**Issue by LuNiPriSe** [clemens/later_dude#2]
Is there a way to tell the script not only the active year and month but also day?

I am using it in the block, but I can not use it for the :current_month parameter. For example:
:current_month => "%a %d.%m%Y" could be a header for my calender

**Comment by clemens** [comment]
Sorry for getting back to you so late – I didn't see the issue.

You could try using a lambda and pass in the current date from outside. Something like this:
@selected = Date.civil(params[:year], params[:month], params[:day])
...
:current_month => lambda { |day| I18n.l(@selected, :format => '%a %d.%m%Y') }

Not sure if the contexts work here but I think they should. Let me know. :-)

**Comment by clemens** [comment]
Since I got no feedback, I'm assuming everything was alright with my solution => I'll close this. Re-open if necessary!
